### ISSUE TITLE
The picture of other university

### ISSUE THREAD

**Issue by LeeWlving** [TOB-KNPOB/Beamer-LaTeX-Themes#4]
谢谢您的工作，我是一个哈工大的学生，请问如何找到并替换出带有相同风格的beamer呢？

**Comment by LeeWlving** [comment]
请问类似的风格的图片有什么地方可以找到吗？

**Comment by LeeWlving** [comment]
谢谢您的意见，我这里修改了一下图片，制作了一个哈工大的beamer，希望您在检查之后可以合并到项目中，谢谢！overleaf link: https://www.overleaf.com/read/hvntndtpphvt
如有不足之处欢迎斧正。

**Comment by TOB-KNPOB** [comment]
很不错诶，谢谢你呀！

考虑发起一个 pull-request 吗？这样项目的 contributors 那里会显示你😄

**Comment by LeeWlving** [comment]
OK, 我创建了pull-request了，不过在readme部分可能还需要您进行修改，谢谢！

**Comment by TOB-KNPOB** [comment]
感谢🤝😄已经 merge 了👌
readme 加了有关信息，如果你在 overleaf 发布了这个模版的话，记得叫我加一下链接哈
